### ISSUE TITLE
'lxs_touchscreen_pdx234.dtsi' file not found

### ISSUE THREAD

**Issue by hellobbn** [sonyxperiadev/kernel-copyleft-dts#12]
The release `67.x.A.x.xxx` does not contain `lxs_touchscreen_pdx234.dtsi`, which is referenced by: `qcom/kalama-yodo-pdx234_generic.dtsi`, which is referenced by: `qcom/kalama-yodo-pdx234_generic-overlay.dts`

Can you release this file?

**Comment by jerpelea** [comment]
fixed !

Thanks for reporting the issue

Best regards
Alin
