### ISSUE TITLE
New DTS for Xperia 10V

### ISSUE THREAD

**Issue by RoninByte** [sonyxperiadev/kernel-copyleft-dts#15]
Could we get the Android 14 DTS and kernel for the Xperia 10V

**Comment by jerpelea** [comment]
@RoninByte we will check the status and release it ASAP
Best regards
Alin

**Comment by jerpelea** [comment]
https://developerworld.wpp.developer.sony.com/file/download/open-source-archive-for-68-1-a-2-244 has been released and the dts will be released ASAP

**Comment by jerpelea** [comment]
@RoninByte the dts is uploaded
https://github.com/sonyxperiadev/kernel-copyleft-dts/tree/68.1.A.2.xxx

Thanks for your patience
Best regards
Alin
