### ISSUE TITLE
[REQUEST] DTS and Kernel source for 64.2.A.2.215

### ISSUE THREAD

**Issue by log1cs** [sonyxperiadev/kernel-copyleft-dts#16]
Since the release of Android 14 for the Nagara platform, no DTS copylefts have been released yet.

Can I request DTS and kernel source for software version 64.2.A.2.215? Thanks.

(If 64.2.A.2.215 is not available yet, then 64.2.A.2.170 is also okay)

**Comment by jerpelea** [comment]
@log1cs I will upload the DTS and kernel asap

Thanks for the message

Best regards
Alin

**Comment by jerpelea** [comment]
@log1cs 

The copyleft has been published
device tree https://github.com/sonyxperiadev/kernel-copyleft-dts/tree/64.2.A.2.xxx
copyleft https://github.com/sonyxperiadev/kernel-copyleft/tree/64.2.A.2.xxx
copyleft archive https://developerworld.wpp.developer.sony.com/file/download/open-source-archive-for-64-2-a-2-170

Thanks for your message 

Best regards
Alin
