### ISSUE TITLE
dts files for 61.1.A.11.36 ?

### ISSUE THREAD

**Issue by hellobbn** [sonyxperiadev/kernel-copyleft-dts#3]
Hi, are you able to release dts files for Xperia 1 III Android 12, specifically, for version 61.1.A.11.36?

**Comment by hellobbn** [comment]
Thanks very much!

**Comment by hellobbn** [comment]
Thanks for uploading it!

**Comment by jerpelea** [comment]
@hellobbn any issues?

**Comment by hellobbn** [comment]
sry, misclick/
