### ISSUE TITLE
[REQUEST] DTS files for 62.1.A.0.675

### ISSUE THREAD

**Issue by Mashopy** [sonyxperiadev/kernel-copyleft-dts#4]
Hello, could it be possible to release DTS files for the Xperia 10 III from 62.1.A.0.675 version ?

**Comment by jerpelea** [comment]
Hi
I will try to do it this week
Best regards
Alin

**Comment by jerpelea** [comment]
hi,
the dts should be ready today
Sorry for the delay 
Best regards
Alin

**Comment by jerpelea** [comment]
done
