### ISSUE TITLE
[REQUEST] DTS files for 61.2.A.0.382 

### ISSUE THREAD

**Issue by lolipuru** [sonyxperiadev/kernel-copyleft-dts#6]
Hello, is dts files for xperia 1 / 5 iii (61.2.A.0.382) release yet? currently there's no both dts and kernel source for that

**Comment by jerpelea** [comment]
Hi,
I will investigate and come back 
Best regards
Alin

**Comment by jerpelea** [comment]
@lolipuru 
The copylefts are generated and should become ASAP
Thanks for reporting the issue
Best regards
Alin

**Comment by lolipuru** [comment]
alright, thanks. (i thought there'll be dts for a13 but seem like it's fine for now, ig)
