### ISSUE TITLE
[REQUEST] DTS source for 65.1.A.4.8

### ISSUE THREAD

**Issue by SpectreDev-007** [sonyxperiadev/kernel-copyleft-dts#9]
Hi Alin,

Could you possibly release the DTS source code for PDX225,

Thanks,

Kindest Regards,
Mohammad

**Comment by jerpelea** [comment]
Hi,
the dts will be released after the copylefts are published. 
Best regards
Alin

**Comment by SpectreDev-007** [comment]
Ok thanks

**Comment by SpectreDev-007** [comment]
> Hi, the dts will be released after the copylefts are published. Best regards Alin

Hi, the copylefts have been published, could you please release the dts

**Comment by jerpelea** [comment]
@SpectreDev-007 they will come ASAP 
Best regards
Alin

**Comment by SpectreDev-007** [comment]
Ok Thanks
